using System.Collections.ObjectModel;

namespace Bibliomatic_MAUI_App.Models
{
    public static class FormulasCategories
    {
        public static ObservableCollection<FormulaCategory> FormulaCategories = new ObservableCollection<FormulaCategory>()
        {
            new FormulaCategory { Category = "Brackets", Formulas = new ObservableCollection<Formula>()
            {
                new Formula { Latex = @"\left ( \frac{a}{b} \right )", Description = "Parenthesis", FormulaImageSource = "brackets_1_b.svg", ImageScale = 2 },
                new Formula { Latex = @"\left[ \frac{a}{b} \right]", Description = "Bracket", FormulaImageSource = "brackets_2_b.svg", ImageScale = 2 },
                new Formula { Latex = @"\left \langle \frac{a}{b} \right \rangle", Description = "Angle bracket", FormulaImageSource = "brackets_3_b.svg", ImageScale = 2 },
                new Formula { Latex = @"\left\{ \frac{a}{b} \right\}", Description = "Brace", FormulaImageSource = "brackets_4_b.svg", ImageScale = 2 },
            }},
            new FormulaCategory { Category = "Fractions-Matrices-Multilines", Formulas = new ObservableCollection<Formula>()
            {
                new Formula { Latex = @"\frac{1}{10}=0.1", Description = "Fractions", FormulaImageSource = "fractions_matrices_multilines_7_f.svg", ImageScale = 2 },
                new Formula { Latex = @"\binom{n}{k}", Description = "Binomial coefficients", FormulaImageSource = "fractions_matrices_multilines_12_f.svg", ImageScale = 2 },
                new Formula { Latex = @"\begin{matrix} x & y \\ z & v \end{matrix}", Description = "Matrices", FormulaImageSource = "fractions_matrices_multilines_15_f.svg", ImageScale = 2 },
                new Formula { Latex = @"\begin{vmatrix} x & y \\ z & v \end{vmatrix}", Description = null, FormulaImageSource = "fractions_matrices_multilines_16_f.svg", ImageScale = 2 },
                new Formula { Latex = @"\begin{Vmatrix} x & y \\ z & v \end{Vmatrix}", Description = null, FormulaImageSource = "fractions_matrices_multilines_17_f.svg", ImageScale = 2 },
                new Formula { Latex = @"\begin{bmatrix} 0 & \cdots & 0 \\ \vdots & \ddots & \vdots \\ 0 & \cdots & 0 \end{bmatrix}", Description = null, FormulaImageSource = "fractions_matrices_multilines_18_f.svg", ImageScale = 1.5 },
                new Formula { Latex = @"\begin{Bmatrix} x & y \\ z & v \end{Bmatrix}", Description = null, FormulaImageSource = "fractions_matrices_multilines_19_f.svg", ImageScale = 2 },
                new Formula { Latex = @"\binom{n}{k}", Description = null, FormulaImageSource = "fractions_matrices_multilines_20_f.svg", ImageScale = 1.5 },
                new Formula { Latex = @"\begin{pmatrix} x & y \\ z & v \end{pmatrix}", Description = null, FormulaImageSource = "fractions_matrices_multilines_21_f.svg", ImageScale = 2 },
                new Formula { Latex = @"\begin{array}{ccc} a & b & S \\ 0&0&1\\ 0&1&1\\ 1&0&1\\ 1&1&0 \end{array}", Description = "Arrays", FormulaImageSource = "fractions_matrices_multilines_22_f.svg", ImageScale = 2 },
                new Formula { Latex = @"\begin{cases} 3x + 5y + z &= 1 \\ 7x - 2y + 4z &= 2 \\ -6x + 3y + 2z &= 3 \end{cases}", Description = "Simultaneous equations", FormulaImageSource = "fractions_matrices_multilines_23_f.svg", ImageScale = 1 },
                new Formula { Latex = @"\begin{array}{lcl} z & = & a \\ f(x,y,z) & = & x + y + z \end{array}", Description = "Multiline equations(left alignment)", FormulaImageSource = "fractions_matrices_multilines_24_f.svg", ImageScale = 1 },
                new Formula { Latex = @"\begin{array}{lcr} z & = & a \\ f(x,y,z) & = & x + y + z \end{array}", Description = "Multiline equations(right alignment)", FormulaImageSource = "fractions_matrices_multilines_25_f.svg", ImageScale = 1 },
            }},
            new FormulaCategory { Category = "Functions", Formulas = new ObservableCollection<Formula>()
            {
                new Formula { Latex = @"\sin\theta", Description = null, FormulaImageSource = "functions_26_f.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\cos\theta", Description = null, FormulaImageSource = "functions_27_f.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\tan\theta", Description = null, FormulaImageSource = "functions_28_f.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\cot", Description = null, FormulaImageSource = "functions_29_f.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\sec", Description = null, FormulaImageSource = "functions_30_f.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\csc", Description = null, FormulaImageSource = "functions_31_f.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\arcsin\frac{L}{r}", Description = null, FormulaImageSource = "functions_32_f.svg", ImageScale = 1.5 },
                new Formula { Latex = @"\arccos\frac{T}{r}", Description = null, FormulaImageSource = "functions_33_f.svg", ImageScale = 1.5 },
                new Formula { Latex = @"\arctan\frac{L}{T}", Description = null, FormulaImageSource = "functions_34_f.svg", ImageScale = 1.5 },
                new Formula { Latex = @"\sinh g", Description = null, FormulaImageSource = "functions_35_f.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\cosh h", Description = null, FormulaImageSource = "functions_36_f.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\tanh i", Description = null, FormulaImageSource = "functions_37_f.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\operatorname{sh}j", Description = null, FormulaImageSource = "functions_38_f.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\max H", Description = null, FormulaImageSource = "functions_39_f.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\min L", Description = null, FormulaImageSource = "functions_40_f.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\inf s", Description = null, FormulaImageSource = "functions_41_f.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\sup t", Description = null, FormulaImageSource = "functions_42_f.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\exp\!t", Description = null, FormulaImageSource = "functions_43_f.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\ln X", Description = null, FormulaImageSource = "functions_44_f.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\lg X", Description = null, FormulaImageSource = "functions_45_f.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\log X", Description = null, FormulaImageSource = "functions_46_f.svg", ImageScale = 2.5 },
                new Formula { Latex = @"f \ker g", Description = null, FormulaImageSource = "functions_47_f.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\log_{10}", Description = null, FormulaImageSource = "functions_48_f.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\log_\alpha X", Description = null, FormulaImageSource = "functions_49_f.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\deg x", Description = null, FormulaImageSource = "functions_50_f.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\arg x", Description = null, FormulaImageSource = "functions_51_f.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\dim x", Description = null, FormulaImageSource = "functions_52_f.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\lim_{t\to n}T", Description = null, FormulaImageSource = "functions_53_f.svg", ImageScale = 2.5 },
            }},
            new FormulaCategory { Category = "Geometric", Formulas = new ObservableCollection<Formula>()
            {
                new Formula { Latex = @"\Box", Description = "Box", FormulaImageSource = "geometric_54_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\Diamond", Description = "Diamond", FormulaImageSource = "geometric_55_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\triangle", Description = "Triangle", FormulaImageSource = "geometric_56_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\angle", Description = "Angle", FormulaImageSource = "geometric_57_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\perp", Description = "Perpendicularity", FormulaImageSource = "geometric_58_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\mid", Description = null, FormulaImageSource = "geometric_59_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\nmid", Description = null, FormulaImageSource = "geometric_60_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\|", Description = null, FormulaImageSource = "geometric_61_g.svg", ImageScale = 2.5 },
            }},
            new FormulaCategory { Category = "Greek alphabet", Formulas = new ObservableCollection<Formula>()
            {
                new Formula { Latex = @"\Gamma", Description = null, FormulaImageSource = "greek_alphabet_62_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\Theta", Description = null, FormulaImageSource = "greek_alphabet_63_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\Xi", Description = null, FormulaImageSource = "greek_alphabet_64_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\Sigma", Description = null, FormulaImageSource = "greek_alphabet_65_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\Phi", Description = null, FormulaImageSource = "greek_alphabet_66_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\Omega", Description = null, FormulaImageSource = "greek_alphabet_67_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\alpha", Description = null, FormulaImageSource = "greek_alphabet_68_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\gamma", Description = null, FormulaImageSource = "greek_alphabet_69_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\epsilon", Description = null, FormulaImageSource = "greek_alphabet_70_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\eta", Description = null, FormulaImageSource = "greek_alphabet_71_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\iota", Description = null, FormulaImageSource = "greek_alphabet_72_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\lambda", Description = null, FormulaImageSource = "greek_alphabet_73_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\nu", Description = null, FormulaImageSource = "greek_alphabet_74_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\omicron", Description = null, FormulaImageSource = "greek_alphabet_75_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\rho", Description = null, FormulaImageSource = "greek_alphabet_76_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\tau", Description = null, FormulaImageSource = "greek_alphabet_77_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\upsilon", Description = null, FormulaImageSource = "greek_alphabet_78_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\chi", Description = null, FormulaImageSource = "greek_alphabet_79_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\omega", Description = null, FormulaImageSource = "greek_alphabet_80_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\varepsilon", Description = null, FormulaImageSource = "greek_alphabet_81_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\vartheta", Description = null, FormulaImageSource = "greek_alphabet_82_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\varpi", Description = null, FormulaImageSource = "greek_alphabet_83_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\Delta", Description = null, FormulaImageSource = "greek_alphabet_84_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\Lambda", Description = null, FormulaImageSource = "greek_alphabet_85_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\Pi", Description = null, FormulaImageSource = "greek_alphabet_86_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\Upsilon", Description = null, FormulaImageSource = "greek_alphabet_87_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\Psi", Description = null, FormulaImageSource = "greek_alphabet_88_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\beta", Description = null, FormulaImageSource = "greek_alphabet_89_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\delta", Description = null, FormulaImageSource = "greek_alphabet_90_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\zeta", Description = null, FormulaImageSource = "greek_alphabet_91_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\theta", Description = null, FormulaImageSource = "greek_alphabet_92_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\kappa", Description = null, FormulaImageSource = "greek_alphabet_93_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\mu", Description = null, FormulaImageSource = "greek_alphabet_94_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\xi", Description = null, FormulaImageSource = "greek_alphabet_95_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\pi", Description = null, FormulaImageSource = "greek_alphabet_96_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\sigma", Description = null, FormulaImageSource = "greek_alphabet_97_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\phi", Description = null, FormulaImageSource = "greek_alphabet_98_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\psi", Description = null, FormulaImageSource = "greek_alphabet_99_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\digamma", Description = null, FormulaImageSource = "greek_alphabet_100_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\varkappa", Description = null, FormulaImageSource = "greek_alphabet_101_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\varrho", Description = null, FormulaImageSource = "greek_alphabet_102_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\varphi", Description = null, FormulaImageSource = "greek_alphabet_103_g.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\varsigma", Description = null, FormulaImageSource = "greek_alphabet_104_g.svg", ImageScale = 2.5 },
            }},
            new FormulaCategory { Category = "Logic-Arrows", Formulas = new ObservableCollection<Formula>()
            {
                new Formula { Latex = @"\And", Description = null, FormulaImageSource = "logic_arrows_105_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\bar{q}", Description = null, FormulaImageSource = "logic_arrows_106_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\lnot", Description = null, FormulaImageSource = "logic_arrows_107_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\wedge", Description = null, FormulaImageSource = "logic_arrows_108_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\vee", Description = null, FormulaImageSource = "logic_arrows_109_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\setminus", Description = null, FormulaImageSource = "logic_arrows_110_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\leftarrow", Description = null, FormulaImageSource = "logic_arrows_111_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\to", Description = null, FormulaImageSource = "logic_arrows_112_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\leftrightarrow", Description = null, FormulaImageSource = "logic_arrows_113_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\longrightarrow", Description = null, FormulaImageSource = "logic_arrows_114_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\longmapsto", Description = null, FormulaImageSource = "logic_arrows_115_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\hookleftarrow", Description = null, FormulaImageSource = "logic_arrows_116_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\searrow", Description = null, FormulaImageSource = "logic_arrows_117_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\nwarrow", Description = null, FormulaImageSource = "logic_arrows_118_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\downarrow", Description = null, FormulaImageSource = "logic_arrows_119_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\Leftarrow", Description = null, FormulaImageSource = "logic_arrows_120_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\Leftrightarrow", Description = null, FormulaImageSource = "logic_arrows_121_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\Longrightarrow", Description = null, FormulaImageSource = "logic_arrows_122_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\land", Description = null, FormulaImageSource = "logic_arrows_123_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\lor", Description = null, FormulaImageSource = "logic_arrows_124_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\neg q", Description = null, FormulaImageSource = "logic_arrows_125_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\bigwedge", Description = null, FormulaImageSource = "logic_arrows_126_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\bigvee", Description = null, FormulaImageSource = "logic_arrows_127_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\smallsetminus", Description = null, FormulaImageSource = "logic_arrows_128_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\gets", Description = null, FormulaImageSource = "logic_arrows_129_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\rightarrow", Description = null, FormulaImageSource = "logic_arrows_130_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\longleftarrow", Description = null, FormulaImageSource = "logic_arrows_131_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\mapsto", Description = null, FormulaImageSource = "logic_arrows_132_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\hookrightarrow", Description = null, FormulaImageSource = "logic_arrows_133_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\nearrow", Description = null, FormulaImageSource = "logic_arrows_134_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\swarrow", Description = null, FormulaImageSource = "logic_arrows_135_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\uparrow", Description = null, FormulaImageSource = "logic_arrows_136_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\updownarrow", Description = null, FormulaImageSource = "logic_arrows_137_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\Rightarrow", Description = null, FormulaImageSource = "logic_arrows_138_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\Longleftarrow", Description = null, FormulaImageSource = "logic_arrows_139_l.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\Longleftrightarrow", Description = null, FormulaImageSource = "logic_arrows_140_l.svg", ImageScale = 2.5 },
            }},
            new FormulaCategory { Category = "Operators", Formulas = new ObservableCollection<Formula>()
            {
                new Formula { Latex = @"\pm", Description = "Plus-minus", FormulaImageSource = "operators_141_o.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\times", Description = "Times", FormulaImageSource = "operators_142_o.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\div", Description = "Division", FormulaImageSource = "operators_143_o.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\neq", Description = "Not equal", FormulaImageSource = "operators_144_o.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\approx", Description = "Approximate", FormulaImageSource = "operators_145_o.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\equiv", Description = "Equivalent", FormulaImageSource = "operators_146_o.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\not\equiv", Description = "Not equivalent", FormulaImageSource = "operators_147_o.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\geq", Description = "Geqslant", FormulaImageSource = "operators_148_o.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\gg", Description = null, FormulaImageSource = "operators_149_o.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\leq", Description = "Leqslant", FormulaImageSource = "operators_150_o.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\ll", Description = null, FormulaImageSource = "operators_151_o.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\sim", Description = "Similar", FormulaImageSource = "operators_152_o.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\simeq", Description = null, FormulaImageSource = "operators_153_o.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\cong", Description = null, FormulaImageSource = "operators_154_o.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\propto", Description = "Propto", FormulaImageSource = "operators_155_o.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\perp", Description = "Perpendicularity", FormulaImageSource = "operators_156_o.svg", ImageScale = 2.5 },
            }},
            new FormulaCategory { Category = "Roots", Formulas = new ObservableCollection<Formula>()
            {
                new Formula { Latex = @"\sqrt{5}", Description = "Square root", FormulaImageSource = "root_157_r.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\sqrt[n]{5}", Description = "nth roots", FormulaImageSource = "root_158_r.svg", ImageScale = 2.5 },
            }},
            new FormulaCategory { Category = "Sets", Formulas = new ObservableCollection<Formula>()
            {
                new Formula { Latex = @"\forall", Description = null, FormulaImageSource = "sets_159_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\in", Description = null, FormulaImageSource = "sets_160_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\subset", Description = null, FormulaImageSource = "sets_161_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\supset", Description = null, FormulaImageSource = "sets_162_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\sqsupset", Description = null, FormulaImageSource = "sets_163_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\cup", Description = null, FormulaImageSource = "sets_164_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\sqcup", Description = null, FormulaImageSource = "sets_165_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\cap", Description = null, FormulaImageSource = "sets_166_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\sqsubset", Description = null, FormulaImageSource = "sets_167_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\varnothing", Description = null, FormulaImageSource = "sets_168_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\emptyset", Description = null, FormulaImageSource = "sets_169_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\notin", Description = null, FormulaImageSource = "sets_170_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\exists", Description = null, FormulaImageSource = "sets_171_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\ni", Description = null, FormulaImageSource = "sets_172_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\subseteq", Description = null, FormulaImageSource = "sets_173_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\supseteq", Description = null, FormulaImageSource = "sets_174_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\sqsupseteq", Description = null, FormulaImageSource = "sets_175_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\bigcup", Description = null, FormulaImageSource = "sets_176_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\bigsqcup", Description = null, FormulaImageSource = "sets_177_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\bigcap", Description = null, FormulaImageSource = "sets_178_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\sqsubseteq", Description = null, FormulaImageSource = "sets_179_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\biguplus", Description = null, FormulaImageSource = "sets_180_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\sqcap", Description = null, FormulaImageSource = "sets_181_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\setminus", Description = null, FormulaImageSource = "sets_182_s.svg", ImageScale = 2.5 },
            }},
            new FormulaCategory { Category = "Special symbols", Formulas = new ObservableCollection<Formula>()
            {
                new Formula { Latex = @"\And", Description = null, FormulaImageSource = "special_183_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\%", Description = null, FormulaImageSource = "special_184_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\ddagger", Description = null, FormulaImageSource = "special_185_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\cdots", Description = null, FormulaImageSource = "special_186_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\smile", Description = null, FormulaImageSource = "special_187_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\wr", Description = null, FormulaImageSource = "special_188_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\triangleright", Description = null, FormulaImageSource = "special_189_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\bot", Description = null, FormulaImageSource = "special_190_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\vdash", Description = null, FormulaImageSource = "special_191_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\Vdash", Description = null, FormulaImageSource = "special_192_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\lVert", Description = null, FormulaImageSource = "special_193_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\imath", Description = null, FormulaImageSource = "special_194_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\ell", Description = null, FormulaImageSource = "special_195_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\Finv", Description = null, FormulaImageSource = "special_196_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\Im", Description = null, FormulaImageSource = "special_197_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\complement", Description = null, FormulaImageSource = "special_198_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\diamondsuit", Description = null, FormulaImageSource = "special_199_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\clubsuit", Description = null, FormulaImageSource = "special_200_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\Game", Description = null, FormulaImageSource = "special_201_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\eth", Description = null, FormulaImageSource = "special_202_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\dagger", Description = null, FormulaImageSource = "special_203_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\ldots", Description = null, FormulaImageSource = "special_204_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\colon", Description = null, FormulaImageSource = "special_205_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\frown", Description = null, FormulaImageSource = "special_206_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\triangleleft", Description = null, FormulaImageSource = "special_207_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\infty", Description = null, FormulaImageSource = "special_208_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\top", Description = null, FormulaImageSource = "special_209_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\vDash", Description = null, FormulaImageSource = "special_210_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\models", Description = null, FormulaImageSource = "special_211_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\rVert", Description = null, FormulaImageSource = "special_212_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\hbar", Description = null, FormulaImageSource = "special_213_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\mho", Description = null, FormulaImageSource = "special_214_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\Re", Description = null, FormulaImageSource = "special_215_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\wp", Description = null, FormulaImageSource = "special_216_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\heartsuit", Description = null, FormulaImageSource = "special_217_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\spadesuit", Description = null, FormulaImageSource = "special_218_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\flat", Description = null, FormulaImageSource = "special_219_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\sharp", Description = null, FormulaImageSource = "special_220_s.svg", ImageScale = 2.5 },
            }},
            new FormulaCategory { Category = "Superscripts-Subscripts-Integrals", Formulas = new ObservableCollection<Formula>()
            {
                new Formula { Latex = @"a^2", Description = "Superscript", FormulaImageSource = "superscripts_subscripts_integrals_221_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"a_2", Description = "Subscript", FormulaImageSource = "superscripts_subscripts_integrals_222_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"a^{2+2}", Description = "Grouping", FormulaImageSource = "superscripts_subscripts_integrals_223_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"x_2^5", Description = "Combining sub & super", FormulaImageSource = "superscripts_subscripts_integrals_224_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"{}_1^2\!X_3^4", Description = "Preceding sub & super", FormulaImageSource = "superscripts_subscripts_integrals_225_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\bigcap_1^{n} p", Description = "Intersections", FormulaImageSource = "superscripts_subscripts_integrals_226_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\bigcup_1^{k} p", Description = "Unions", FormulaImageSource = "superscripts_subscripts_integrals_227_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"x'", Description = "Derivatives", FormulaImageSource = "superscripts_subscripts_integrals_228_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\dot{x}", Description = "Derivative dots", FormulaImageSource = "superscripts_subscripts_integrals_229_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\ddot{y}", Description = null, FormulaImageSource = "superscripts_subscripts_integrals_230_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\vec{c}", Description = "Vectors", FormulaImageSource = "superscripts_subscripts_integrals_231_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\overleftarrow{a b}", Description = null, FormulaImageSource = "superscripts_subscripts_integrals_232_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\overrightarrow{c d}", Description = null, FormulaImageSource = "superscripts_subscripts_integrals_233_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\widehat{e f g}", Description = null, FormulaImageSource = "superscripts_subscripts_integrals_234_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\overline{h i j}", Description = "Overline", FormulaImageSource = "superscripts_subscripts_integrals_236_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\underline{k l m}", Description = "Underline", FormulaImageSource = "superscripts_subscripts_integrals_237_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\sum_{k=1}^N k^2", Description = "Sum", FormulaImageSource = "superscripts_subscripts_integrals_240_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\prod_{i=1}^N x_i", Description = "Product", FormulaImageSource = "superscripts_subscripts_integrals_241_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\coprod_{i=1}^N x_i", Description = "Coproduct", FormulaImageSource = "superscripts_subscripts_integrals_242_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\lim_{n \to \infty}x_n", Description = "Limit", FormulaImageSource = "superscripts_subscripts_integrals_243_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\int_{-N}^{N} e^x\, dx", Description = "Integral", FormulaImageSource = "superscripts_subscripts_integrals_244_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\iint_{D}^{W} \, dx\,dy", Description = "Double integral", FormulaImageSource = "superscripts_subscripts_integrals_245_s.svg", ImageScale = 2.5 },
                new Formula { Latex = @"\iiint_{E}^{V} \, dx\,dy\,dz", Description = "Triple integral", FormulaImageSource = "superscripts_subscripts_integrals_246_s.svg", ImageScale = 1.5 },
                new Formula { Latex = @"\oint_{C} x^3\, dx + 4y^2\, dy", Description = "Quadruple integral", FormulaImageSource = "superscripts_subscripts_integrals_247_s.svg", ImageScale = 1.5},
            }},
        };
    }
}
